[Intellisense] Support citation intellisense from .bib file
iamhyc/Overleaf-Workshop pull request #87
Opened 2024-01-22 08:57 UTC by QianrenLi

> resolve #61 
This PR is aim to support bib entry completition from bib file.

## TODOS

- [x]  Provide a tree structure to manage the file symbols in the project

## Modification
### `src/intellisense/texDocSymbolTree.ts`
In this file, define the `FileNode`, `FileSymbolTree` two new structure. 
- `FileNode`, representing an abstract file entity, contains comonents like:
  -  file path, derived from Uri.path, used to identify each file.
  -  document symbols, extracted from `parseNode` in `texDocSymbolProvider.ts`
  -  bibFilePath, the file path of bib file used in this `.tex` file
  -  parent, the file path of parent node; If this value if undefined, this node is either root node or node not included in the project.
  -  children, the array of file path of children node.
- `FileSymbolTree`, the manager of all the Nodes in project opened
  - `fileNodeMap` which is a map `Map<string, FileNode>` used to reduced the time required to get each node.
  - `rootPath` the file path of root node. 
  - func `insertSymbol` used to insert symbol to tree where a new parent-child relation is created.
  - func `updateSymbol` used to update the node in the tree structure by replacing `fileNodeMap` and parent-child relation.
  - func `bfs` provide a breath traverse function which can be used to traverse the tree.

2024-01-22 09:16 UTC, iamhyc commented on src/intellisense/texDocSymbolTree.ts
> +    filePath: string,
define `type FilePath = string;`

2024-01-22 09:17 UTC, iamhyc commented on src/intellisense/texDocSymbolTree.ts
> +    parent?: string,
- use the `type FilePath`
- use `null` for root node not `undefined`

2024-01-22 10:54 UTC, iamhyc requested changes

2024-01-22 10:54 UTC, iamhyc commented on src/intellisense/texDocSymbolTree.ts
> +    parent?: TeXElement,
remove `parent` and `children`

2024-01-22 10:54 UTC, iamhyc commented on src/intellisense/texDocSymbolTree.ts
> +        private rootPath?:string,
don't use single root, maintain forest instead.

2024-01-22 10:54 UTC, iamhyc commented on src/intellisense/texDocSymbolTree.ts
> +    public getRoot(): FileNode | undefined {
remove this function

2024-01-22 10:54 UTC, iamhyc commented on src/intellisense/texDocSymbolTree.ts
> +    public getSymbol(filePath: string): FileNode | undefined {
use `get` for attribute get

2024-01-22 10:54 UTC, iamhyc commented on src/intellisense/texDocSymbolTree.ts
> +    public hasSymbol(filePath:string): boolean {
remove this function, use `get` attribute function instead

2024-01-22 10:54 UTC, iamhyc commented on src/intellisense/texDocSymbolTree.ts
> +    public updateSymbol(fileNode: FileNode): void {
why `filePath` not needed here?

2024-01-22 10:54 UTC, iamhyc commented on src/intellisense/texDocSymbolTree.ts
> +    public async bfs( callback: (node: FileNode) => Promise<void> ): Promise<void> {
remove this function, useless.

2024-01-23 07:39 UTC, iamhyc requested changes

2024-01-23 07:39 UTC, iamhyc commented on src/intellisense/texDocSymbolTree.ts
> +    set parentPath(parentPath: string | undefined){
remove all set/get function, and make all attributes public

2024-01-26 08:29 UTC, iamhyc approved these changes

2024-01-26 08:29 UTC, iamhyc commented on src/intellisense/texDocSymbolCache.ts
> +    public fileNodeCache: Map<string, FileCache> = new Map<string, FileCache>();
public or private?

2024-01-26 08:40 UTC, QianrenLi commented on src/intellisense/texDocSymbolCache.ts
> +    public fileNodeCache: Map<string, FileCache> = new Map<string, FileCache>();
Should be private, fixed

2024-01-26 09:02 UTC, iamhyc approved these changes

2024-01-26 12:01 UTC, closed without merging

2024-01-26 12:23 UTC, iamhyc commented
@QianrenLi push the full implementation, I will approve it regardless of the code quality. no draft conversion any more.

2024-01-26 12:25 UTC, QianrenLi commented
OK